# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c80d5685dfa9851651c83094365332bde1faaa1ef3945993252401010e4729f83a30019a9ce9405d8c85ee49d1905497331697949b36afc4cf7633cae919aa1

test:
  secret_key_base: 0d1a2023c4db3bfb359e6f0f878c36db614beec565f0cb2cc4e0337f646019fabdb23aab0205d9d4b3201799abf7f072fd7dcf919ddb4d9c88161ee4e65b6683

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
